# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Self-Hosted-Pool

steps:
- script: jupyter nbconvert --to notebook --execute Data_Collector.ipynb
  displayName: 'Run the data collector'

- script: jupyter nbconvert --to notebook --execute MachineAlgorithms.ipynb
  displayName: 'Run the machine learning'
